
services:
  api_gateway:
    build:
      context: ./api_gateway
    ports:
      - "8080:8080"
    env_file:
      - ./api_gateway/.env
    depends_on:
      - team_service


  team_service:
    build:
      context: ./team_service
    ports:
      - "8000:8000"
    env_file:
      - ./team_service/.env
    volumes:
      - ./team_service:/app