# Generated by Django 5.1.6 on 2025-07-21 16:17

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.UUIDField(default=uuid.UUID('a84de5ab-f48f-4b9f-81ff-d4383822df1d'), primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('deadline', models.DateTimeField()),
                ('status', models.CharField(choices=[('Pending', 'pending'), ('In_Progress', 'in_progress'), ('Completed', 'completed')], default='pending', max_length=20)),
                ('assigned_to', models.IntegerField()),
                ('assigned_by', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
